name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    pull_request:
      types: [opened, synchronize, reopened]
jobs:
  name: SonarCloud
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Dependencies
      run: bun
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}